# Generated by Django 3.2.14 on 2022-09-07 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_auto_20220906_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='castcrew',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
