# Generated by Django 3.2.14 on 2022-07-26 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_alter_genre_options'),
    ]

    operations = [

    ]
